import NavBar from "@/components/navBar/NavBar";
import { Inter } from "next/font/google";
import Footer from "@/components/footer/Footer";
import Provider from "@/Provider";
import Page from "./page";
import Loading from "./loading";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Blog",
  description: "Generated by create next app",
};

export default function BlogLayout({children}) {
  return (
      <section className={inter.className}>
        <Provider>
          <NavBar />
          <Suspense fallback={<Loading />}>
            {children}
          </Suspense>
        </Provider>
      </section>
  );
}
